### ISSUE TITLE
FAILURE: Build failed with an exception with NativeScript4 RC

### ISSUE THREAD

**Issue by p-3** [dapriett/nativescript-google-maps-sdk#265] opened 2018-04-06 08:51 UTC
We are getting build error on android with nativescript@rc (NativeScript 4). API key's have been set after the documentation, and also googlePlayServicesVersion = "+" app.gradle.

Failed to build plugin nativescript-google-maps-sdk : 
Error: Command failed: ./gradlew -p /Users/p-3/Projects/googlemapswithns4/platforms/tempPlugin/nativescript_google_maps_sdk assembleRelease -PcompileSdk=android-27 -PbuildToolsVersion=26.0.2 -PsupportVersion=26.0.0-alpha1
/Users/p-3/Projects/googlemapswithns4/platforms/tempPlugin/nativescript_google_maps_sdk/build/intermediates/manifests/aapt/release/AndroidManifest.xml:13: AAPT: resource string/nativescript_google_maps_api_key (aka org.nativescript.nativescript_google_maps_sdk:string/nativescript_google_maps_api_key) not found.
    
/Users/p-3/Projects/googlemapswithns4/platforms/tempPlugin/nativescript_google_maps_sdk/build/intermediates/manifests/aapt/release/AndroidManifest.xml:13: error: resource string/nativescript_google_maps_api_key (aka org.nativescript.nativescript_google_maps_sdk:string/nativescript_google_maps_api_key) not found.
error: failed processing manifest.

FAILURE: Build failed with an exception.

**Comment by ferre1987** [comment] 2018-04-10 21:46
+1

**Comment by cuapio18** [comment] 2018-04-10 22:55
+1

**Comment by dapriett** [comment] 2018-04-11 02:48
Looks like they moved App_Resources in v4:

https://github.com/NativeScript/android-runtime/blob/master/CHANGELOG.md

Have you tried running the following command from the documentation?

`tns resources update android`

**Comment by isaacfi** [comment] 2018-04-11 04:02
I have tried:

`tns resources update android`

but I have the same problem

**Comment by ugunenc** [comment] 2018-04-11 10:07
The only way that i can run is  uncommenting line in
nodemodules/nativescript-google-maps-sdk/paltforms/android/res/values/nativescript_google_maps_api.xml

**Comment by isaacfi** [comment] 2018-04-11 13:11
Which line did you comment? @ugunenc

**Comment by shivgolani** [comment] 2018-04-11 13:53
You can provide the API Key directly in
nodemodules/nativescript-google-maps-sdk/paltforms/android/AndroidManifest.xml line number 9 android:value="your_google_maps_key"

**Comment by ferre1987** [comment] 2018-04-11 21:49
I tried inserting in the AndroidManifest -> android:value="your_google_maps_key"
the error continues to exist

**Comment by racknoris** [comment] 2018-04-12 14:01
I believe i get the exact same error as he does:
```
Execution failed for task ':packageReleaseResources'.
> /Users/myuser/project/platforms/tempPlugin/nativescript_google_maps_sdk/src/main/res/values/nativescript_google_maps_api.xml: Error: In DataSet 'main', no data file for changedFile. This is an internal error in the incremental builds code; to work around it, try doing a full clean build.
```

**Comment by ugunenc** [comment] 2018-04-12 14:16
@isaacfi line 3
`     <string name="nativescript_google_maps_api_key">PUT_API_KEY_HERE</string>
`
i put the api key and run

**Comment by racknoris** [comment] 2018-04-12 14:43
@shivgolani I did that multiple times, the only thing that worked is using your method adding the value to `AndroidManifest.xml`, combined with @ugunenc method of uncommenting and directly inserting the api key.
After the build succeeded i got error of: `Error: com.tns.NativeScriptException: Failed to find module: "@angular/platform-browser-dynamic", relative to: app/tns_modules/`, so at this point i'm going to downgrade to ns 3.4.2 and someday get back to 4+

**Comment by isaacfi** [comment] 2018-04-12 16:58
@racknoris can you share your files and path files please?

**Comment by racknoris** [comment] 2018-04-12 17:02
@isaacfi After downgrading to 3.4.2 i got the exact same error, which made me check `package.json`, and for some reason `@angular/platform-browser-dynamic` was not present, so i added it and now it works in 3.4.2.
I suppose that if i upgrade again to version 4, it'll now work, but i wont do it for some time now

**Comment by ferre1987** [comment] 2018-04-13 19:12
The problem is when launch -> tns build android

the error is: 
`/Documents/myapp/platforms/tempPlugin/nativescript_google_maps_sdk/build/intermediates/manifests/aapt/release/AndroidManifest.xml:13: AAPT: resource string/nativescript_google_maps_api_key (aka org.nativescript.nativescript_google_maps_sdk:string/nativescript_google_maps_api_key) not found.
`

I have in: App_Resources/Android-Pre-v4/vaules/nativescript_google_maps_api.xml
with this code:
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="nativescript_google_maps_api_key">Here my key</string>
</resources>`

I have in: App_Resources/Android-Pre-v4/vaules/strings.xml
with this code:
`<string name="nativescript_google_maps_api_key">Here my key</string>`

I tried to check the file in the platforms: la string nativescript_google_maps_api_key is commenting

**Comment by kessapeutfout** [comment] 2018-04-14 05:07
same result on nativescript 3.4.2 (no angular)

**Comment by dapriett** [comment] 2018-04-16 02:56
Closed by #268

**Closed by dapriett** 2018-04-16 02:56 UTC

**Comment by cnqiuxue** [comment] 2018-05-31 04:03
I have tried:

tns resources update android

but I have the same problem

**Comment by racknoris** [comment] 2018-05-31 04:41
@cnqiuxue what's the error message you're getting?

**Comment by cnqiuxue** [comment] 2018-05-31 05:47
Unable to apply changes on device: emulator-5554. Error is: Failed to build plugin nativescript-google-maps-sdk :
Error: Command ./gradlew failed with exit code 1 Error output:
 Exception in thread "main" java.lang.ClassNotFoundException: org.gradle.launcher.GradleMain
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:29)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by cnqiuxue** [comment] 2018-05-31 05:48
@racknoris  I tried all the above methods, but they didn't work

**Comment by cnqiuxue** [comment] 2018-05-31 05:52
In the package.json file "nativescript-google-maps-sdk": "^2.6.0" delete, the project can run, but can't use maps plug-in

**Comment by racknoris** [comment] 2018-05-31 06:03
Do you get something before `Unable to apply changes...`?

**Comment by cnqiuxue** [comment] 2018-05-31 06:13
@racknoris  That was my simulator. I only turned on the usb developer to debug, and didn't do anything. The Google map of the simulator was just opened to run normally, but the project was still not started.

**Comment by racknoris** [comment] 2018-05-31 06:15
@cnqiuxue i mean, what did you get in the console window before the text of `Unable to apply changes`?

**Comment by cnqiuxue** [comment] 2018-05-31 06:27
![image](https://user-images.githubusercontent.com/26665435/40765300-91582c4e-64de-11e8-9bab-c6fdfbfaea60.png)
I haven't changed any code, just can't use this plugin.

**Comment by racknoris** [comment] 2018-05-31 06:30
ok i see.
now use: `tns run android --log trace` and give me the output after the "Successfully prepared plugin tns-core..."

**Comment by cnqiuxue** [comment] 2018-05-31 06:34
ok ![image](https://user-images.githubusercontent.com/26665435/40765645-af714af2-64df-11e8-99d8-7738e4f6e537.png)

**Comment by cnqiuxue** [comment] 2018-05-31 06:56
@racknoris  Did you see the problem?

**Comment by racknoris** [comment] 2018-05-31 07:39
Did you `the platform remove android` and `the platform remove android`?

**Comment by cnqiuxue** [comment] 2018-05-31 07:45
![image](https://user-images.githubusercontent.com/26665435/40769064-99d39240-64e9-11e8-95fd-dce72a7dc33b.png)

**Comment by cnqiuxue** [comment] 2018-05-31 07:45
I tried, or I couldn't.

**Comment by racknoris** [comment] 2018-05-31 07:54
Sorry, i have no more ideas, hope you'll be able to fix it

**Comment by cnqiuxue** [comment] 2018-05-31 08:07
But thank you, too.

**Comment by coderscoven** [comment] 2018-08-28 10:44
@hackerunet: 
I actually had the same problem. I then realized that your PC is supposed to have internet.
