### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by thiagoterleski** [dapriett/nativescript-google-maps-sdk#69] opened 2016-08-30 14:36 UTC
Hi, 
there are plans for clustering? This feature is very important! :-)

**Comment by dapriett** [comment] 2016-08-30 14:58
There is a feature request out there for it #57 - @naderio mentioned he may work it.  If not, I'll welcome PRs!

**Comment by dapriett** [comment] 2016-08-30 14:58
Duplicate of #57

**Closed by dapriett** 2016-08-30 14:58 UTC

**Comment by naderio** [comment] 2016-09-12 14:53
https://github.com/naderio/nativescript-google-maps-sdk-utils
