### ISSUE TITLE
Can't support NS7 

### ISSUE THREAD

**Issue by taothai** [dapriett/nativescript-google-maps-sdk#439] opened 2020-10-29 12:32 UTC
Can't support NS7

**Comment by dapriett** [comment] 2020-10-29 12:57
Duplicate of #422

**Closed by dapriett** 2020-10-29 12:57 UTC

**Comment by AgustinV08** [comment] 2020-10-29 15:52
@dapriett When will the Nativescript 7 PR will be merged #420?

**Comment by MrSnoozles** [comment] 2020-10-30 13:28
It still needs some more work to be done. As everyone is working on it in their free time there's no guarantee when it can be merged. Sadly :-) But it is on the way.
