### ISSUE TITLE
Exception when using Map inside TabView (Android Angular 2 app)

### ISSUE THREAD

**Issue by ADjenkov** [dapriett/nativescript-google-maps-sdk#165] opened 2017-05-21 13:06 UTC
Hi, 
The map control is working perfect when not inside `TabView` component. If I put it inside tabItem an exception is thrown (see the image).

{N} 3.0.1 Angular 2 Android application (Android 7.1.1 API 25)

![image](https://cloud.githubusercontent.com/assets/5860190/26284244/5f9299e0-3e3f-11e7-9848-0ce8d244250e.png)

**Comment by dapriett** [comment] 2017-05-21 13:11
This is a duplicate of #158.  Looks like you're using an older version of the plugin, should be working now.

**Closed by dapriett** 2017-05-21 13:11 UTC

**Comment by ADjenkov** [comment] 2017-05-21 13:25
@dapriett I apologize for my negligence and the repeating issue. I've just updated to 2.0.6 but now (mapReady) event is not fired and I get "nativeView is not defined". I guess I'm doing something wrong? I've tried to delete node_modules/platforms and rebuild the app.

**Comment by dapriett** [comment] 2017-05-21 17:48
@ADjenkov - sorry, try 2.0.7.  Looks like what got published in npm wasn't matching the repo.  Should be good now.
